<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>PhonePeClone_._Infrastructure</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PhonePeClone . Application\PhonePeClone . Application.csproj" />
    <ProjectReference Include="..\PhonePeClone . Domain\PhonePeClone . Domain.csproj" />
  </ItemGroup>

</Project>
